version: '3.8'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - '${PG_PORT}:${PG_PORT}'
    volumes:
      - ./data-postgres/:/data/postgres

  pgadmin:
    env_file:
      - ./.env
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80'
